/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d-bracelet-object/highres.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/highres.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmpk18hq2spply.geometry} material={nodes.tmpk18hq2spply.material} />
    </group>
  )
}

useGLTF.preload('/highres.glb')
